/* Generated by GOB (v2.0.12)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdk.h>
#include <gtk/gtk.h>

#include "global.h"
#include "generator.h"
#include "comp.h"
#include "sheet.h"
#include "msgbox.h"
#include "control.h"
#include "gencomp.h"
#include "gui.h"

#include "galan-compaction.h"

#ifndef __GALAN_COMPTREE_MODEL_H__
#define __GALAN_COMPTREE_MODEL_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define GALAN_TYPE_COMPTREE_MODEL	(galan_comptree_model_get_type())
#define GALAN_COMPTREE_MODEL(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), galan_comptree_model_get_type(), GalanCompTreeModel)
#define GALAN_COMPTREE_MODEL_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), galan_comptree_model_get_type(), GalanCompTreeModel const)
#define GALAN_COMPTREE_MODEL_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), galan_comptree_model_get_type(), GalanCompTreeModelClass)
#define GALAN_IS_COMPTREE_MODEL(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), galan_comptree_model_get_type ())

#define GALAN_COMPTREE_MODEL_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), galan_comptree_model_get_type(), GalanCompTreeModelClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_GALAN_COMPTREE_MODEL__
#define __TYPEDEF_GALAN_COMPTREE_MODEL__
typedef struct _GalanCompTreeModel GalanCompTreeModel;
#endif
struct _GalanCompTreeModel {
	GtkTreeStore __parent__;
};

/*
 * Class definition
 */
typedef struct _GalanCompTreeModelClass GalanCompTreeModelClass;
struct _GalanCompTreeModelClass {
	GtkTreeStoreClass __parent__;
};


/*
 * Public methods
 */
GType	galan_comptree_model_get_type	(void);
gboolean 	galan_comptree_model_lookup	(GalanCompTreeModel * self,
					char * path,
					GtkTreeIter * iter,
					gboolean create);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
